baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
  identifier = "HOME"
  name = "HOME"
  url = "/"
  weight = 100
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
